# Welcome to Jekyll!

# Website settings
title: Thomas Schmitt
description: Personal website of Thomas Schmitt
keywords: twsthomas, thomas, schmitt, inria, machine learning
# baseurl:  /homepage # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: http://twsthomas.github.io/  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Schmitt  # Be used at blog posts' author.
  first_name: Thomas  # Be used at index page about me section.
  last_name: Schmitt  # Be used at index page about me section.
  avatar: /static/assets/img/landing/TS.jpg  # upload your avatar at directory and edit it.
  github_username: twsthomas  # Leave blank if you don't have now
  linkedin_id: twsthomas # Leave blank if you don't have now
#   facebook_username: jiakunnj  # Leave blank if you don't have now
#   twitter_username: jiakun614  # Leave blank if you don't have now
  email: twsthomas@gmail.com  # Leave blank if you don't have now
#   cv: http://cv.jarrekk.com  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    #- name: icon-shell 
    - name: icon-python
    - name: fa-linux
  skill_icon2:
    - name: fa-github 
    - name: fa-bicycle

  desc: Data Scientist  # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
#   name: jalpc

# analytics
## google analytics
ga:  
  id: UA-146921644-2

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
